FROM apache/airflow:2.9.1

USER root

RUN apt-get update && apt-get install -y docker.io

USER airflow

ADD batch/requirements.txt .

RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
