version: "3.8"

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server 
      --backend-store-uri /mlflow/mlruns 
      --host 0.0.0.0 
      --port 5000

  mlflow-client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mlflow-server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - ./:/app
