channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - pandas==2.0.1
  - psutil==5.9.5
  - scikit-learn==1.5.2
  - scipy==1.10.1
name: mlflow-env
